import React from 'react';
import { ArrowLeft, FileText } from 'lucide-react';
import { PressureLogo } from './PressureLogo';

interface TermsAndConditionsProps {
  onBack: () => void;
}

export const TermsAndConditions: React.FC<TermsAndConditionsProps> = ({ onBack }) => {
  return (
    <div className="w-full min-h-screen bg-[#F6F5F2] text-[#141414] flex flex-col">
      {/* Top Header */}
      <header className="w-full max-w-3xl mx-auto px-6 pt-8 pb-6 flex items-center justify-between">
        <button
          type="button"
          onClick={onBack}
          id="terms-back-btn"
          className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white border border-neutral-200 text-xs font-bold text-neutral-700 hover:text-black hover:border-neutral-300 transition-colors shadow-2xs"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back</span>
        </button>

        <div className="flex items-center gap-2">
          <PressureLogo size="sm" />
          <span className="font-extrabold tracking-tight text-sm">PRESSURE</span>
        </div>
      </header>

      {/* Main Legal Content */}
      <main className="w-full max-w-3xl mx-auto px-6 pb-24 flex-1">
        <div className="bg-white border border-neutral-200/90 rounded-[28px] p-6 sm:p-12 shadow-2xs">
          <div className="mb-8 pb-6 border-b border-neutral-100">
            <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-neutral-100 text-neutral-600 text-xs font-semibold mb-3">
              <FileText className="w-3.5 h-3.5 text-neutral-700" />
              <span>Terms of Service</span>
            </div>
            <h1 className="text-2xl sm:text-4xl font-extrabold text-[#141414] tracking-tight">
              Terms and Conditions
            </h1>
            <p className="text-xs text-neutral-500 mt-2 font-medium">
              Version 1.0 • Last updated: September 2026
            </p>
          </div>

          <div className="prose prose-neutral max-w-none text-sm sm:text-base leading-relaxed text-neutral-700 space-y-8 font-normal">
            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                1. Acceptance of Terms
              </h2>
              <p>
                By accessing or using the PRESSURE application, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these Terms, you must not access or use the application.
              </p>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                2. Description of the Service
              </h2>
              <p>
                PRESSURE provides an AI-assisted decision-support tool designed to help users identify psychological pressure patterns, urgency cues, and potential manipulation tactics in communication screenshots. The tool produces evaluative scores, tactic breakdowns, and reflective pause questions.
              </p>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                3. AI Limitations and No Guarantee of Accuracy
              </h2>
              <p>
                Analyses generated by PRESSURE rely on probabilistic machine learning models provided by Google Gemini. You explicitly acknowledge and agree that:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1.5 text-neutral-600">
                <li>
                  Evaluations are informational only and may contain inaccuracies, false positives, or false negatives.
                </li>
                <li>
                  A low pressure score does not prove that a message is authentic, legitimate, or safe.
                </li>
                <li>
                  A high pressure score does not prove that a sender is fraudulent, malicious, or deceptive.
                </li>
                <li>
                  PRESSURE cannot determine an individual's true inner intentions, identity, or legal culpability.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                4. Not Professional or Emergency Advice
              </h2>
              <p>
                PRESSURE does not provide legal, financial, law enforcement, cybersecurity, or psychological counsel. If you believe you are in immediate physical danger, are experiencing an emergency, or suspect ongoing criminal extortion, contact local emergency services, law enforcement authorities, or your financial institution immediately via official verified numbers.
              </p>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                5. User Responsibilities and Uploaded Content
              </h2>
              <p>
                You retain all rights to any screenshots or text you submit. By uploading content, you represent and warrant that:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1.5 text-neutral-600">
                <li>
                  You possess the lawful right to upload and process the content.
                </li>
                <li>
                  Your upload does not violate intellectual property rights, privacy rights, or statutory laws.
                </li>
                <li>
                  You will exercise your own independent judgment and verify communications through secondary channels prior to taking financial or sensitive actions.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                6. Acceptable Use and Prohibited Conduct
              </h2>
              <p>
                You agree not to use PRESSURE to:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1.5 text-neutral-600">
                <li>
                  Reverse-engineer, decompile, or extract the underlying models or algorithms.
                </li>
                <li>
                  Test or refine malicious phishing lures, social engineering scripts, or fraudulent campaigns.
                </li>
                <li>
                  Perform automated denial-of-service or high-volume scraping attacks against our APIs.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                7. Intellectual Property
              </h2>
              <p>
                All visual assets, trademarks, branding, user interfaces, code, and design architecture associated with PRESSURE are the exclusive property of PRESSURE and its licensors, protected by applicable copyright and trademark laws.
              </p>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                8. Service Availability and Modifications
              </h2>
              <p>
                We reserve the right to modify, suspend, or discontinue the service, in whole or in part, at any time without prior notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuance.
              </p>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                9. Limitation of Liability
              </h2>
              <p>
                To the maximum extent permitted by applicable law, PRESSURE and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your use of, or inability to use, the service, including any reliance placed on AI evaluations or actions taken in response to messages.
              </p>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                10. Changes to Terms
              </h2>
              <p>
                We may revise these Terms from time to time. If we make material modifications, we will increment the terms version number, requiring you to review and accept the updated version before accessing the application dashboard.
              </p>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                11. Governing Law
              </h2>
              <p>
                These Terms shall be governed by and construed in accordance with standard commercial practices and applicable laws, without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-base sm:text-lg font-bold text-[#141414] mb-2">
                12. Contact Information
              </h2>
              <p>
                For questions or inquiries regarding these Terms and Conditions, please reach out to:
              </p>
              <p className="mt-1 font-mono text-xs text-neutral-800">
                <a href="mailto:web3update3y@gmail.com" className="hover:underline text-[#141414]">
                  web3update3y@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
};
